[package]
name = "csv2bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
csv = "1.2.2"
is-terminal = "0.4.9"
